name: Tilt Digital
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48392
title: Tilt Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54479616-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1c1e'
    - '#4ec1a5'
    - '#fefefe'
    - '#2f3438'
    - '#ccced0'
  brandStrength: 0.965215313481167
  lightness: 0.5339116256218404
  saturation: 0.3157314534764737
  rhythmicContrast: 0.2932123951613903
purpose: []
